[package]
name = "rust_audio_capture"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.3"
anyhow = "1.0.86" # エラーハンドリングを簡単にするため追加
